#! /bin/bash

source .env

docker build \
  --build-arg="UBERBASE_DOMAIN=$UBERBASE_DOMAIN" \
  --build-arg UBERBASE_ADMIN_USERNAME \
  --build-arg UBERBASE_ADMIN_EMAIL \
  --build-arg UBERBASE_ADMIN_PASSWORD \
  --build-arg UBERBASE_CADDY_STORAGE \
  --build-arg UBERBASE_REDIS_HOST \
  --build-arg UBERBASE_REDIS_PORT \
  --build-arg UBERBASE_REDIS_SECRET \
  --build-arg UBERBASE_REDIS_STORAGE \
  --build-arg UBERBASE_POSTGRES_HOST \
  --build-arg UBERBASE_POSTGRES_DATABASE \
  --build-arg UBERBASE_POSTGRES_USER \
  --build-arg UBERBASE_POSTGRES_PASSWORD \
  --build-arg UBERBASE_POSTGRES_PORT \
  --build-arg UBERBASE_POSTGRES_STORAGE \
  --build-arg UBERBASE_POSTGREST_VERSION \
  --build-arg UBERBASE_POSTGREST_JWT_SECRET \
  --build-arg UBERBASE_POSTGREST_PORT \
  --build-arg UBERBASE_MINIO_HOST \
  --build-arg UBERBASE_MINIO_PORT \
  --build-arg UBERBASE_MINIO_CONSOLE_PORT \
  --build-arg UBERBASE_MINIO_STORAGE \
  --build-arg UBERBASE_MINIO_ROOT_USER \
  --build-arg UBERBASE_MINIO_ROOT_PASSWORD \
  --build-arg UBERBASE_LOGTO_HOST \
  --build-arg UBERBASE_LOGTO_PUBLIC_PORT \
  --build-arg UBERBASE_LOGTO_ADMIN_PORT \
  --build-arg UBERBASE_LOGTO_DATABASE \
  --build-arg UBERBASE_LOGTO_ENDPOINT \
  --build-arg UBERBASE_LOGTO_ADMIN_ENDPOINT \
  --build-arg UBERBASE_FUNCTIONS_PORT \
  --build-arg UBERBASE_FUNCTIONS_IMAGE_PATH \
  -t bluetongueai/uberbase:latest \
  .
