name: uberbase

volumes:
  redis_data:
  postgres_data:
  minio_data:


services:
  redis:
    restart: always
    image: docker.io/redis/redis-stack:latest
    container_name: redis
    user: "0"
    volumes:
      - ${UBERBASE_REDIS_STORAGE}:/data:Z
      - ${PWD}/logs:/var/log/redis:Z
    ports:
      - ${UBERBASE_REDIS_PORT}:6379
    env_file:
      - .env
    #environment:
    #  REDIS_ARGS: "--logfile /var/log/redis/redis.log --loglevel verbose"
    network_mode: host

  postgres:
    restart: always
    image: docker.io/library/postgres:16.2
    container_name: postgres
    environment:
      POSTGRES_USER: ${UBERBASE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${UBERBASE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${UBERBASE_POSTGRES_DATABASE}
    env_file:
      - .env
    ports:
      - ${UBERBASE_POSTGRES_PORT}:5432
    command: -c config_file=/etc/postgresql/postgresql.conf
    volumes:
      - ${PWD}/logs:/var/log/postgresql
      - ${PWD}/configs/postgres/init:/docker-entrypoint-initdb.d
      - ${PWD}/postgres/conf:/etc/postgresql/
      - ${UBERBASE_POSTGRES_STORAGE}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${UBERBASE_POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    network_mode: host

  minio:
    restart: always
    image: quay.io/minio/minio:latest
    container_name: minio
    user: "0"
    command: server /data --console-address ":9001"
    volumes:
      - ${UBERBASE_MINIO_STORAGE}:/data:Z
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${UBERBASE_MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${UBERBASE_MINIO_ROOT_PASSWORD}
    ports:
      - ${UBERBASE_MINIO_PORT}:9000
      - ${UBERBASE_MINIO_CONSOLE_PORT}:9001
    network_mode: host

  logto:
    restart: always
    image: docker.io/svhd/logto:latest
    container_name: logto
    entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start 2>&1 > /var/log/logto/logto.log"]
    environment:
      - TRUST_PROXY_HEADER=1
      - DB_URL=postgres://postgres:postgres@localhost:5432/logto
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ${PWD}/logs:/var/log/logto
    ports:
      - ${UBERBASE_LOGTO_PUBLIC_PORT}:3001
      - ${UBERBASE_LOGTO_ADMIN_PORT}:3002
    network_mode: host
 
  postgrest:
    restart: always
    image: docker.io/bluetongueai/postgrest:latest
    container_name: postgrest
    build:
      context: ./postgrest
      args:
        - POSTGREST_VERSION=${UBERBASE_POSTGREST_VERSION}
    env_file:
      - .env
    volumes:
      - ${PWD}/configs/postgrest/postgrest.conf:/etc/postgrest.conf
      - ${PWD}/logs:/var/log/postgrest
    ports:
      - ${UBERBASE_POSTGREST_PORT}:3000
    depends_on:
      postgres:
        condition: service_healthy
    network_mode: host
