name: uberbase

networks:
  net:
    driver: bridge

volumes:
  redis_data:
  postgres_data:


services:

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - redis_data:/data
      - ./logs/redis:/var/log:Z
    ports:
      - ${UBERBASE_REDIS_PORT}:6379
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - net

  postgres:
    image: postgres:16.2
    container_name: postgres
    environment:
      POSTGRES_USER: ${UBERBASE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${UBERBASE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${UBERBASE_POSTGRES_DATABASE}
    env_file:
      - .env
    ports:
      - ${UBERBASE_POSTGRES_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init/:/docker-entrypoint-initdb.d/
      - ./logs/postgres:/var/log
    networks:
      - net

  lldap:
    image: lldap/lldap:latest-debian-rootless
    container_name: lldap
    entrypoint: "/bin/bash -C /app/docker-entrypoint.sh &> /var/log/lldap.log"
    ports:
      - ${UBERBASE_LLDAP_ADMIN_PORT}:17170
    depends_on:
      - postgres
    volumes:
      - ./configs/lldap:/data
      - ./logs/lldap:/var/log
    env_file:
      - .env
    networks:
      - net

  authelia:
    image: authelia/authelia
    ports:
      - ${UBERBASE_AUTHELIA_PORT}:9091
    volumes:
      - ./configs/authelia:/config
      - ./logs/authelia:/var/log
    env_file:
      - .env
    depends_on:
      - postgres
      - lldap
      - redis
    networks:
      - net

  caddy:
    image: caddy:2.8.4
    ports:
      - ${UBERBASE_HTTP_PORT}:80
      - ${UBERBASE_HTTPS_PORT}:443
    volumes:
      - ./configs/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./logs/caddy:/var/log
    depends_on:
      - authelia
    env_file:
      - .env
    networks:
      - net

  postgrest:
    image: uberbase/postgrest:latest
    build:
      context: ./postgrest
      args:
        - POSTGREST_VERSION=${UBERBASE_POSTGREST_VERSION}
    env_file:
      - .env
    volumes:
      - ./configs/postgrest/postgrest.conf:/etc/postgrest.conf
    ports:
      - ${UBERBASE_POSTGREST_PORT}:3000
    depends_on:
      - postgres
    networks:
      - net

  studio:
    image: uberbase/studio:latest
    build:
      context: ./studio
    ports:
      - ${UBERBASE_STUDIO_PORT}:3000
    env_file:
      - .env
    networks:
      - net
