services:

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - ./redis:/data
    networks:
      - net
    expose:
      - 6379
    restart: unless-stopped

  postgres:
    image: postgres:16.2
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - ${UBERBASE_POSTGRES_PORT}:5432
    volumes:
      - ./data:/var/lib/postgresql/data

  lldap:
    image: lldap/lldap:stable
    container_name: lldap
    ports:
      - ${UBERBASE_LLDAP_ADMIN_PORT}:17170
    depends_on:
      - postgres

  authelia:
    image: authelia/authelia
    ports:
      - ${UBERBASE_AUTHELIA_PORT}:9091
    volumes:
      - ./authelia:/config

  caddy:
    image: caddy:2.4.5
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - authelia

  postgrest:
    image: postgrest/postgrest:8.0.0
    environment:
      PGRST_DB_URI: "postgres://postgres:postgres@postgres:5432/postgres"
      PGRST_DB_SCHEMA: "public"
      PGRST_DB_ANON_ROLE: "postgres"
      PGRST_SERVER_PORT: "3000"

  openfaas:
    image: openfaas/faasd:0.13.0
