name: uberbase

networks:
  net:
    driver: bridge

volumes:
  redis_data:
  postgres_data:
  minio_data:
  caddy_data:


services:
  redis:
    restart: always
    image: docker.io/redis/redis-stack:latest
    container_name: redis
    user: "0"
    volumes:
      - ${UBERBASE_REDIS_STORAGE}:/data:Z
      - ${PWD}/logs:/var/log/redis:Z
    ports:
      - ${UBERBASE_REDIS_PORT}:6379
    # entrypoint: redis-server --requirepass ${UBERBASE_REDIS_SECRET} --logfile /var/log/redis/redis.log --loglevel verbose
    env_file:
      - .env
    networks:
      - net

  postgres:
    restart: always
    image: docker.io/library/postgres:16.2
    container_name: postgres
    user: ${UID}:${GID}
    environment:
      POSTGRES_USER: ${UBERBASE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${UBERBASE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${UBERBASE_POSTGRES_DATABASE}
    env_file:
      - .env
    ports:
      - ${UBERBASE_POSTGRES_PORT}:5432
    # entrypoint: postgres -c logging_collector=on -c log_directory=/var/log/postgres -c log_statement=all -c log_filename=postgresql.log
    volumes:
      - ${UBERBASE_POSTGRES_STORAGE}:/var/lib/postgresql/data:Z
      - ${PWD}/configs/postgres/init:/docker-entrypoint-initdb.d
      - ${PWD}/logs:/var/log/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${UBERBASE_POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - net

  minio:
    restart: always
    image: quay.io/minio/minio:latest
    container_name: minio
    user: "0"
    command: server /data --console-address ":9001"
    volumes:
      - ${UBERBASE_MINIO_STORAGE}:/data:Z
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${UBERBASE_MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${UBERBASE_MINIO_ROOT_PASSWORD}
    ports:
      - ${UBERBASE_MINIO_PORT}:9000
      - ${UBERBASE_MINIO_CONSOLE_PORT}:9001
    networks:
      - net

  caddy:
    restart: always
    image: docker.io/caddy:2.8.4
    container_name: caddy
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ${PWD}/configs/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ${PWD}/logs:/var/log/caddy
      - ${UBERBASE_CADDY_DATA}:/data/caddy
    env_file:
      - .env
    networks:
      - net

  logto:
    restart: always
    image: docker.io/svhd/logto:latest
    container_name: logto
    entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start"]
    environment:
      - TRUST_PROXY_HEADER=1
      - DB_URL=postgres://postgres:postgres@postgres:5432/logto
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - ${UBERBASE_LOGTO_PUBLIC_PORT}:3001
      - ${UBERBASE_LOGTO_ADMIN_PORT}:3002
    networks:
      - net
 
  postgrest:
    restart: always
    image: docker.io/bluetongueai/postgrest:latest
    container_name: postgrest
    build:
      context: ./postgrest
      args:
        - POSTGREST_VERSION=${UBERBASE_POSTGREST_VERSION}
    env_file:
      - .env
    volumes:
      - ${PWD}/configs/postgrest/postgrest.conf:/etc/postgrest.conf
      - ${PWD}/logs:/home/podman/app/logs/postgrest
    ports:
      - ${UBERBASE_POSTGREST_PORT}:3000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - net
