name: uberbase

networks:
  net:
    driver: bridge

volumes:
  redis_data:
  postgres_data:


services:

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - redis_data:/data
      - ${PWD}/logs:/var/log/redis:Z
    #ports:
    #  - ${UBERBASE_REDIS_PORT}:6379
    restart: unless-stopped
    entrypoint: redis-server --requirepass ${UBERBASE_REDIS_SECRET} --logfile /var/log/redis/redis.log --loglevel verbose
    env_file:
      - .env
    networks:
      - net

  postgres:
    image: postgres:16.2
    container_name: postgres
    user: postgres
    environment:
      POSTGRES_USER: ${UBERBASE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${UBERBASE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${UBERBASE_POSTGRES_DATABASE}
    env_file:
      - .env
    #ports:
    #  - ${UBERBASE_POSTGRES_PORT}:5432
    entrypoint: postgres -c logging_collector=on -c log_directory=/var/log/postgres -c log_statement=all -c log_filename=postgresql.log
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ${PWD}/postgres/init/00_init_ultrabase.sql:/docker-entrypoint-initdb.d/00_init_ultrabase.sql
      - ${PWD}/logs:/var/log/postgres
    networks:
      - net

  lldap:
    image: lldap/lldap:latest-debian-rootless
    container_name: lldap
    entrypoint: /bin/bash -c "/docker-entrypoint.sh run --config-file /data/lldap_config.toml > /var/log/lldap/lldap.log 2>&1"
    #ports:
    #  - ${UBERBASE_LLDAP_ADMIN_PORT}:17170
    depends_on:
      - postgres
    volumes:
      - ${PWD}/configs/lldap:/data
      - ${PWD}/logs:/var/log/lldap
    env_file:
      - .env
    networks:
      - net

  authelia:
    image: authelia/authelia
    #ports:
    #  - ${UBERBASE_AUTHELIA_PORT}:9091
    volumes:
      - ${PWD}/configs/authelia:/config
      - ${PWD}/logs:/var/log/authelia
    env_file:
      - .env
    depends_on:
      - postgres
      - lldap
      - redis
    networks:
      - net

  caddy:
    image: caddy:2.8.4
    ports:
      - ${UBERBASE_HTTP_PORT}:80
      - ${UBERBASE_HTTPS_PORT}:443
    volumes:
      - ${PWD}/configs/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ${PWD}/logs:/var/log/caddy
    depends_on:
      - authelia
    env_file:
      - .env
    networks:
      - net

  postgrest:
    image: uberbase/postgrest:latest
    build:
      context: ./postgrest
      args:
        - POSTGREST_VERSION=${UBERBASE_POSTGREST_VERSION}
    env_file:
      - .env
    volumes:
      - ${PWD}/configs/postgrest/postgrest.conf:/etc/postgrest.conf
      - ${PWD}/logs:/var/log/postgrest
    #ports:
    #  - ${UBERBASE_POSTGREST_PORT}:3000
    depends_on:
      - postgres
    networks:
      - net

  studio:
    image: uberbase/studio:latest
    build:
      context: ./studio
    #ports:
    #  - ${UBERBASE_STUDIO_PORT}:3000
    env_file:
      - .env
    volumes:
      - ${PWD}/logs:/var/log/studio
    networks:
      - net
