providers:
  file:
    directory: /etc/traefik/config/dynamic
    watch: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  letsencryptresolver:
    acme:
      email: ${UBERBASE_ADMIN_EMAIL}
      storage: /data/acme.json
      tlsChallenge: true

