log:
  level: INFO

accessLog: {}

providers:
  file:
    directory: /etc/traefik/config/dynamic/
    watch: true

entryPoints:
  web:
    address: ":${UBERBASE_TRAEFIK_HTTP_PORT}"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":${UBERBASE_TRAEFIK_HTTPS_PORT}"
    http:
      tls:
        certResolver: letsencryptresolver

certificatesResolvers:
  letsencryptresolver:
    acme:
      email: ${UBERBASE_ADMIN_EMAIL}
      storage: /data/acme.json
      tlsChallenge: true

serversTransport:
  rootCAs:
    - /uberbase/certs/ca.crt
