http:
  services:
    auth:
      loadBalancer:
        servers:
        - url: "http://${UBERBASE_FUSIONAUTH_HOST}:${UBERBASE_FUSIONAUTH_PORT}/"
    api:
      loadBalancer:
        servers:
        - url: "http://${UBERBASE_POSTGREST_HOST}:${UBERBASE_POSTGREST_PORT}/"
    storage:
      loadBalancer:
        servers:
        - url: "http://${UBERBASE_MINIO_HOST}:${UBERBASE_MINIO_CONSOLE_PORT}/"
  
  routers:
    auth:
      rule: "Host(`auth.${UBERBASE_DOMAIN}`)"
      service: auth
    api:
      rule: "Host(`api.${UBERBASE_DOMAIN}`)"
      service: api
    storage:
      rule: "Host(`storage.${UBERBASE_DOMAIN}`)"
      service: storage

