#!/bin/bash

#-v /proc:/proc:rw \

docker run --rm -it \
  -v ${PWD}:/home/podman/app \
  -v podman_data:/var/lib/podman \
  --security-opt seccomp=unconfined \
  --device /dev/fuse \
  --device /dev/net/tun \
  --cap-add MKNOD \
  --cap-add SYS_ADMIN \
  --cap-add NET_ADMIN \
  --cap-add SETUID \
  --cap-add SETGID \
  --entrypoint=/bin/bash \
  -p 8080:80 \
  -p 8443:443 \
  bluetongueai/uberbase:latest
