#!/bin/bash

docker run \
  -d \
  --rm \
  --name uberbase \
  --security-opt seccomp=unconfined \
  --device /dev/fuse \
  --device /dev/net/tun \
  --cap-add MKNOD \
  --cap-add SYS_ADMIN \
  --cap-add NET_ADMIN \
  --cap-add SETUID \
  --cap-add SETGID \
  -v uberbase_test_podman_data:/home/podman/podman \
  -v uberbase_test_uberbase_data:/home/podman/app/data \
  -p 8080:80 \
  -p 8443:443 \
  bluetongueai/uberbase:latest

docker logs -f uberbase
