#!/bin/bash

docker run --rm \
  -d \
  --name uberbase \
  --security-opt seccomp=unconfined \
  --device /dev/fuse \
  --device /dev/net/tun \
  --cap-add MKNOD \
  --cap-add SYS_ADMIN \
  --cap-add NET_ADMIN \
  --cap-add SETUID \
  --cap-add SETGID \
  -v podman_data:/home/podman/.podman \
  -p 8080:80 \
  -p 8443:443 \
  bluetongueai/uberbase:latest

docker logs -f uberbase
