version = 2
disabled_plugins = ["io.containerd.grpc.v1.cri"]
root = "/var/lib/firecracker-containerd/containerd"
state = "/run/firecracker-containerd"
[grpc]
  address = "/run/firecracker-containerd/containerd.sock"
[plugins]
  [plugins."io.containerd.snapshotter.v1.devmapper"]
    root_path = "/var/lib/firecracker-containerd/snapshotter/devmapper"
    pool_name = "vg0-containerd--thinpool"
    base_image_size = "18GB"
[debug]
  level = "debug"
